### PR TITLE
Test using a submitted system profile

### PR DESCRIPTION
**Pull request by pilhuhn**
Signed-off-by: Heiko W. Rupp <hrupp@redhat.com>

### CODE REVIEW

**Comment by josejulio** [comment]
I get the following when running `mvn package`
```
[ERROR] Tests run: 3, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 12.969 s <<< FAILURE! - in com.redhat.cloud.custompolicies.engine.PolicyEvalTest
[ERROR] test1Match  Time elapsed: 0.051 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected status code <200> but was <412>.

        at com.redhat.cloud.custompolicies.engine.PolicyEvalTest.test1Match(PolicyEvalTest.java:147)

[ERROR] testEvalSystemProfile  Time elapsed: 0.073 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected status code <200> but was <412>.

        at com.redhat.cloud.custompolicies.engine.PolicyEvalTest.testEvalSystemProfile(PolicyEvalTest.java:168)

2019-11-28 12:24:56,206 INFO  [org.apa.kaf.cli.con.int.AbstractCoordinator] (vert.x-kafka-consumer-thread-0) [Consumer clientId=consumer-1, groupId=8a8e10b0-8b1b-4026-a4f1-a7e1369355b4] Member consumer-1-641b3ffc-9d9b-4bf4-aec9-7d65be3cc6d2 sending LeaveGroup request to coordinator localhost:9092 (id: 2147483647 rack: null)
2019-11-28 12:24:56,214 INFO  [org.apa.kaf.cli.pro.KafkaProducer] (vert.x-worker-thread-0) [Producer clientId=producer-1] Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
2019-11-28 12:24:56,221 INFO  [io.sma.rea.mes.ext.MediatorManager] (main) Cancel subscriptions
2019-11-28 12:24:56,225 INFO  [io.quarkus] (main) Quarkus stopped in 0.052s
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   PolicyEvalTest.test1Match:147 1 expectation failed.
Expected status code <200> but was <412>.

[ERROR]   PolicyEvalTest.testEvalSystemProfile:168 1 expectation failed.
Expected status code <200> but was <412>.

[INFO] 
[ERROR] Tests run: 28, Failures: 2, Errors: 0, Skipped: 0

```

**Comment by pilhuhn** [comment]
Strange. I am looking into it.

**Comment by pilhuhn** [comment]
I can't reproduce what you saw, but have changed the behavior anyway.
Also I was locally running into https://github.com/quarkusio/quarkus/issues/5878 - the latest commit has a workaround.

**Comment by josejulio** [comment]
Running the test within Intellij does not fail and you can't reproduce it. I'm going to check my environment, maybe I have something old/wrong.

**Pull request merged**
